# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FPStaticServer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FPStaticServer
  
  pod "GCDWebServer", "~> 3.0"

end
